/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'yun_dev1' at '16. 3. 18 오후 6:34' with Gradle 2.8
 *
 * @author yun_dev1, @date 16. 3. 18 오후 6:34
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
